- alias: Toilet - Turn on lights when movement
  trigger:
  - entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
    platform: state
    to: '8'
  action:
  - service: light.turn_on
    data:
      entity_id: light.toilet
      brightness: 20

- alias: Toilet - Turn off light when movement stops
  trigger:
  - entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
    platform: state
    to: '0'
    for:
      minutes: 2
  action:
  - service: light.turn_off
    data:
      entity_id: light.toilet

- alias: Living room TV - paused
  trigger:
  - entity_id: media_player.living_room_tv
    platform: state
    to: 'idle'
  - entity_id: media_player.living_room_tv
    platform: state
    to: 'paused'
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: template
      value_template: "{{ states.media_player.living_room_tv.attributes.app_name in ['YouTube', 'Netflix'] }}"
  action:
    service: hue.hue_activate_scene
    data:
      group_name: 'Living room'
      scene_name: 'Bright'

- alias: Living room TV - playing
  trigger:
  - entity_id: media_player.living_room_tv
    platform: state
    to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: template
      value_template: "{{ states.media_player.living_room_tv.attributes.app_name in ['YouTube', 'Netflix'] }}"
  action:
    service: hue.hue_activate_scene
    data:
      group_name: 'Living room'
      scene_name: 'Dimmed'

- alias: Stairs Cupboard - Turn on when sensor open
  trigger:
  - entity_id: sensor.stairs_door_access_control
    platform: state
    to: '22'
  action:
  - service: light.turn_on
    data:
      entity_id: light.stairs
      brightness: 20

- alias: Stairs Cupboard - Turn off when door closed
  trigger:
  - entity_id: sensor.stairs_door_access_control
    platform: state
    to: '23'
  action:
  - service: light.turn_off
    data:
      entity_id: light.stairs

