- alias: Toilet - Turn on lights when movement
  trigger:
  - entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
    platform: state
    to: '8'
  action:
  - service: light.turn_on
    data:
      entity_id: light.toilet
      brightness: 20

- alias: Toilet - Turn off light when movement stops
  trigger:
  - entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
    platform: state
    to: '0'
    for:
      minutes: 2
  action:
  - service: light.turn_off
    data:
      entity_id: light.toilet
